DuckDB 제대로 쓰기

In [1]:
import duckdb
import pandas as pd

In [2]:
# DB 연결
con = duckdb.connect(database='D:/Assets/BinanceFuturesData/binancefuturesdata.duckdb', read_only=True)

In [6]:
# DB 연결 해제
con.close()

In [ ]:
# 타임스탬프(ms) -> 날짜
pd.to_datetime(1718590260000, unit='ms')

Timestamp('2024-06-17 02:11:00')

In [5]:
r1 = con.execute("SELECT * FROM symbol where name = 'BTCSTUSDT'").df()
r1

,name,liquidation_fee,listing_date,max_price,min_price,tick_size,max_quantity,min_quantity,step_size,price_precision,quantity_precision,underlying_type
0,BTCSTUSDT,0.04,1614754800000,100000.0,0.668,0.001,1000000.0,0.1,0.1,3,1,Coin

In [11]:
r2 = con.execute("select * from quote where symbol = 'BTCSTUSDT' order by timestamp desc limit 100").df()
r2

,symbol,interval,timestamp,open,high,low,close,volume,quote_volume,taker_buy_volume,taker_buy_quote_volume,trade_count
0,BTCSTUSDT,1,1718590260000,319.408,319.408,319.408,319.408,0.0,0.0,0.0,0.0,0
1,BTCSTUSDT,1,1718590200000,319.408,319.408,319.408,319.408,0.0,0.0,0.0,0.0,0
2,BTCSTUSDT,1,1718590140000,319.408,319.408,319.408,319.408,0.0,0.0,0.0,0.0,0
3,BTCSTUSDT,1,1718590080000,319.408,319.408,319.408,319.408,0.0,0.0,0.0,0.0,0
4,BTCSTUSDT,1,1718590020000,319.408,319.408,319.408,319.408,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,BTCSTUSDT,1,1718584560000,319.408,319.408,319.408,319.408,0.0,0.0,0.0,0.0,0
96,BTCSTUSDT,1,1718584500000,319.408,319.408,319.408,319.408,0.0,0.0,0.0,0.0,0
97,BTCSTUSDT,1,1718584440000,319.408,319.408,319.408,319.408,0.0,0.0,0.0,0.0,0
98,BTCSTUSDT,1,1718584380000,319.408,319.408,319.408,319.408,0.0,0.0,0.0,0.0,0
99,BTCSTUSDT,1,1718584320000,319.408,319.408,319.408,319.408,0.0,0.0,0.0,0.0,0

In [5]:
r3 = con.execute("PRAGMA table_info(quote)").df()
r3

    cid                    name           type  notnull dflt_value     pk
0     0                  symbol        VARCHAR     True       None   True
1     1                interval        TINYINT     True       None   True
2     2               timestamp         BIGINT     True       None   True
3     3                    open  DECIMAL(18,8)    False       None  False
4     4                    high  DECIMAL(18,8)    False       None  False
5     5                     low  DECIMAL(18,8)    False       None  False
6     6                   close  DECIMAL(18,8)    False       None  False
7     7                  volume  DECIMAL(24,8)    False       None  False
8     8            quote_volume  DECIMAL(18,8)    False       None  False
9     9        taker_buy_volume  DECIMAL(24,8)    False       None  False
10   10  taker_buy_quote_volume  DECIMAL(18,8)    False       None  False
11   11             trade_count        INTEGER    False       None  False